### PR TITLE
fix #25

### LINKED ISSUE #25: Thumbs aren't working in IE
Thumbs aren't displaying in IE because of using angular expressions in thumb's attribute 'style'. It should be replaced by 'ng-style'.

### PR DESCRIPTION
**Pull request by TheLegion**
I replaced thumb's attribute 'style' with directive 'ng-style'
Works fine on IE 11, Google Chrome, Mozilla Firefox.

### CODE REVIEW

**Comment by thatisuday** [comment]
@TheLegion merged and version incremented. If you test it, let me know here. Btw, working fine on preview.

**Comment by TheLegion** [comment]
I've test it, works good. Thank you :)

**Comment by thatisuday** [comment]
@TheLegion If is it possible for you, take a look at https://github.com/thatisuday/ng-image-gallery/issues/28 where ng-style is also needed.

**Comment by TheLegion** [comment]
Ok, I'll fix #28.
The angular dependency in bower.json has version ^1.5.7 while the angular-animate has version 1.5.7. Is it right?

**Comment by thatisuday** [comment]
@TheLegion Yes. Feel free to change it to 1.5.8 if you want

**Pull request merged**
