### PR TITLE
Use ng-bind-html for title and desc

### PR DESCRIPTION
**Pull request by msieurtoph**
(sorry for the change due to my SublimeText plugin which automatically deletes trailing spaces)

### CODE REVIEW

**Comment by thatisuday** [comment]
@msieurtoph Have you tested this?

**Comment by msieurtoph** [comment]
Yes I did.
It works like a charm with simple html tags (like `<b>`, `<i>`, `<a>`, ... ).

With more complex html templates, the user will probably have to use `$sce.trustAs()` before using it ...

**Comment by thatisuday** [comment]
@msieurtoph Yes, that was my concern. You need to implement `$sce.trustAs()` else we will again get new issue asking for the same. Plz implement that  and give new PR. :)

**Comment by msieurtoph** [comment]
Done ;)
I also fixed the provider configuration example, using the array annotation mode. I spent sometimes trying to understand why I couldn't uglify my scripts ;)
I hope you don't mind.

**Comment by thatisuday** [comment]
@msieurtoph I am getting some conflicts in dist files. Can you take a pull and run gulp build task again. Would be great...

**Comment by msieurtoph** [comment]
Done!
I also applied the ngImagegalleryTrust on the placeholder ... :)

**Pull request merged**
